apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-demo
spec:
  containers:
  - name: container1
    image: busybox
    command: ['sh', '-c', 'echo "Container 1 starting"; sleep 60']
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

  - name: container2
    image: busybox
    command: ['sh', '-c', 'echo "Container 2 starting"; sleep 120']
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

  - name: container3
    image: busybox
    command: ['sh', '-c', 'echo "Container 3 starting"; sleep 180']
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
  
  restartPolicy: Never