apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-demo
spec:
  containers:
  - name: container1
    image: busybox
    command: ['sh', '-c', 'echo "Container 1 starting"; sleep 60']
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

  - name: container2
    image: busybox
    command: ['sh', '-c', 'echo "Container 2 starting"; sleep 120']
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

  - name: container3
    image: busybox
    command: ['sh', '-c', 'echo "Container 3 starting"; sleep 180']
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
  
  restartPolicy: Never

  ---

  apiVersion: batch/v1
kind: Job
metadata:
  name: short-lived-job
spec:
  template:
    metadata:
      labels:
        app: short-lived-job
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 1"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      restartPolicy: Never
  backoffLimit: 0
